---
title: "Demo20161016"
author: "David Chiu"
date: "2016/10/16"
output: html_document
---

# load sparkR
```{r}
# 設定SparkR 環境變數
if (nchar(Sys.getenv("SPARK_HOME")) < 1) {
  Sys.setenv(SPARK_HOME = "/usr/local/spark")
}

# 載入SparkR
library(SparkR, lib.loc = c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib")))

# 　本地端啟用
sparkR.session(master = "local[*]" ,sparkConfig =                                          list(
                        spark.sql.shuffle.partitions = "3",
                        spark.default.parallelism="2",
                        spark.cores.max = "1"))

```

## 讀取資料
```{r}

download.file('https://github.com/ywchiu/sparkr/raw/master/data/lvr_prices.csv', destfile = 'lvr_prices.csv')
lvr_prices <- read.csv('~/lvr_prices.csv', header=TRUE)

View(lvr_prices)

class(lvr_prices)

str(lvr_prices)

```

## Data visualization
```{r}
hist(lvr_prices$total_price)
boxplot(lvr_prices$total_price)

hist(log10(lvr_prices$total_price))
boxplot(log10(lvr_prices$total_price))

```

## Convert R DataFrame to Spark Data Frame
```{r}
?as.DataFrame
lvr_data <- as.DataFrame(lvr_prices)

head(lvr_data)

?showDF
showDF(lvr_data)

class(lvr_data)
printSchema(lvr_data)


```

# dplyr
```{r}
# install.packages('dplyr')
library(dplyr)

str(lvr_prices)
# R Style
head(lvr_prices[,c('area', 'total_price')])

# dplyr Style
head(select(lvr_prices, area, total_price))

detach("package:dplyr", unload=TRUE)
# SparkR Style
head(select(lvr_data, lvr_data$area, lvr_data$total_price))

# R Style
head(lvr_prices[lvr_prices$area == '大安區',])

# dplyr Style
library(dplyr)
head(filter(lvr_prices, area == '大安區'))

detach("package:dplyr", unload=TRUE)
# SparkR Style
head(filter(lvr_data, lvr_data$area == '大安區'))


```

# magrittr
```{r}
# install.packages('magrittr')
library(magrittr)

# R Style
head(lvr_prices[lvr_prices$area == '大安區', c('area', 'total_price') ])


# head(select(lvr_prices, area, total_price))

library(dplyr)
# dplyr style
lvr_prices %>% select(area, total_price) %>% head()

detach("package:dplyr", unload=TRUE)
# SparkR Style
lvr_data %>% select(lvr_data$area, lvr_data$total_price) %>% head()


lvr_data %>% 
  select(lvr_data$area, lvr_data$total_price) %>%
  filter(lvr_data$area == '大安區') %>% 
  　head()

# head(summarize(groupBy(lvr_data, lvr_data$area), price_sum = sum(lvr_data$total_price)))

lvr_data %>% groupBy(lvr_data$area) %>% 
  summarize(price_sum = sum(lvr_data$total_price)) %>%
  head()


#summarize(groupBy(lvr_data, lvr_data$area), price_sum = sum(lvr_data$total_price)) %>% arrange(desc(.$price_sum)) %>% head()
lvr_data %>% groupBy(lvr_data$area) %>% 
  summarize(price_sum = sum(lvr_data$total_price)) %>%
  arrange(desc(.$price_sum)) %>% 
  head()

lvr_data %>% groupBy(lvr_data$area) %>% 
  summarize(price_sum = mean(lvr_data$price_per_sqmeter)) %>%
  arrange(desc(.$price_sum)) %>% 
  head()




```

#@ datediff
```{r}
lvr_data$house_age <- (datediff(date_format(lvr_data$trading_ymd, "yyyy-MM-dd"), date_format(lvr_data$finish_ymd, "yyyy-MM-dd")))/ 365

```

## gapply, gapplycollect
```{r}
schema <- structType(structField("area", "string"), structField("total_price", "double"))

# gapply => transformation
result <- gapply(
  lvr_data,
  "area",
  function(key, x) {
    y <- data.frame(key, sum(x$total_price), stringsAsFactors = FALSE)
  },
  schema)

head(collect(arrange(result, "total_price", decreasing = TRUE)))
class(result) # Spark DataFrame


# gapplycollect => action
result <- gapplyCollect(
  lvr_data,
  "area",
  function(key, x) {
    y <- data.frame(key, sum(x$total_price))
    colnames(y) <- c("area", "sum_price")
    y
  })

 class(result) # R dataframe
```

# SparkSQL
```{r}
createOrReplaceTempView(lvr_data, "lvr_data")

lvr_sql <- sql("
      SELECT area, avg(total_price) 
        FROM lvr_data 
       WHERE house_age < 30 
    GROUP BY area
    ORDER BY avg(total_price) DESC")

class(lvr_sql)
head(lvr_sql)
```

# 根據各區計算每月平均價格變化
```{r}
#取得交易年月資料
lvr_data$trading_ym <- date_format(lvr_data$trading_ymd, "yyyy-MM-01")

#根據區域與年月計算平均交易價格
mean_prices <- 
        summarize(
          groupBy(lvr_data, lvr_data$area, lvr_data$trading_ym),
          price_avg = mean(lvr_data$total_price)
        )

#取得平均價格
 mean_df <- collect(mean_prices)
 mean_df$trading_ym <- as.Date(mean_df$trading_ym)
 
 par(mfrow= c(3,4))
 for (a in unique(mean_df$area)){
  new_df = mean_df[mean_df$area == a, ] 
  plot(sort(new_df$trading_ym), new_df$price_avg[order(new_df$trading_ym)]  , main = a, type='l', col= 'red', margin = 0.1)
}

```

# Machine Learning On diabetic data
```{r}
#download.file('https://github.com/ywchiu/sparkr/raw/master/data/diabetic_sample.csv', 'diabetic_sample.csv')

#diabetes = read.csv('diabetic_sample.csv')
#View(diabetes)


#install.packages('lars')
library(lars)
data(diabetes)


diabetes_all <- data.frame(cbind(diabetes$x, y = diabetes$y))
outcome_name <- 'y'
diabetes_all$sex <- as.numeric(as.factor(diabetes_all$sex ))

```

# split into training and testing dataset
```{r}
set.seed(1234)
splitIndex <- base::sample(nrow(diabetes_all),
floor(0.75*nrow(diabetes_all)))

## 331 as training
train_diabetes <- diabetes_all[ splitIndex,]

## 111 as testing
test_diabetes <- diabetes_all[-splitIndex,]


train_diabetes_sp <- createDataFrame(train_diabetes)

test_diabetes_sp <- createDataFrame(test_diabetes)

class(train_diabetes_sp)
class(test_diabetes_sp)
```

# regression model
```{r}
model <- glm(y~age+sex+bmi+map+tc+ldl+hdl+tch+ltg+glu,
data=train_diabetes_sp, family='gaussian')
class(model)

summary(model)


predictions <- predict(model, newData = test_diabetes_sp)
names(predictions)

test_output <- collect(test_diabetes_sp)
predictions_ = test_output$y
predictions_details <- collect(predictions)
mse <- mean(predictions_details$label - predictions_details$prediction)

```

# house prediction
```{r}

set.seed(1234)
splitIndex <- base::sample(nrow(lvr_prices),
floor(0.75*nrow(lvr_prices)))

## 24401 as training
train_lvr <- lvr_prices[ splitIndex,]

## 8134 as testing
test_lvr <- lvr_prices[-splitIndex,]


train_lvr_sp <- createDataFrame(train_lvr)

test_lvr_sp <- createDataFrame(test_lvr)

paste(names(lvr_prices), collapse = "+")

model <- glm(total_price~area+building_sqmeter,
data=train_lvr_sp, family='gaussian')

class(model)

summary(model)


```




# stop sparkr
```{r}
sparkR.stop()
```


