---
title: "Demo20170212"
author: "David Chiu"
date: "2017/2/12"
output: html_document
---
## Setup SparkR
```{r}
# 設定SparkR 環境變數
if (nchar(Sys.getenv("SPARK_HOME")) < 1) {
  Sys.setenv(SPARK_HOME = "/usr/local/spark")
}

# 載入SparkR
library(SparkR, lib.loc = c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib")))

# Start Cluster
sparkR.session(master = "spark://master:7077", 
               sparkConfig = list(spark.executor.memory = "600m", 
                                  spark.sql.shuffle.partitions = "3",
                                  spark.default.parallelism="2"))

lvr_prices <- read.csv('lvr_prices.csv')
head(lvr_prices)
class(lvr_prices)

lvr_data <- as.DataFrame(lvr_prices)
printSchema(lvr_data)

SparkR::head(SparkR::select(lvr_data, "total_price"))
SparkR::head(SparkR::filter(lvr_data, lvr_data$area=='大安區'))

```

## Advanced Spark Operation
```{r}

col <- SparkR::select(lvr_data, "total_price")
col
SparkR::head(col)

filt <- SparkR::filter(lvr_data, lvr_data$area=='大安區')
filt
printSchema(filt)
SparkR::head(filt)


```
## %>%
```{r}

SparkR::head(SparkR::filter(SparkR::select(lvr_data, "total_price"), lvr_data$area=='大安區'))

library(magrittr)
class(lvr_data)
lvr_data %>% 
  SparkR::select("total_price", "area") %>% 
  SparkR::filter(lvr_data$area=='大安區') %>% 
  head()

?collect
lvr_data %>% 
  SparkR::select("total_price", "area") %>% 
  SparkR::filter(lvr_data$area=='大安區') %>%
  SparkR::collect()
  

install.packages("dplyr")
library(dplyr)
class(lvr_prices)
lvr_prices %>% 
  dplyr::select(total_price, area) %>%
  dplyr::filter(area=='大安區') %>%
  head()

```

## Aggregation
```{r}

detach("package:dplyr", unload=TRUE)
head(summarize(group_by(lvr_data, "area"), price_sum=sum(lvr_data$total_price)))

taipei_house <- lvr_data %>% 
  group_by("area") %>%
  summarize(price_sum = sum(lvr_data$total_price)) %>%
  collect()

taipei_house


taipei_house_mean <- lvr_data %>% 
  group_by("area") %>%
  summarize(price_mean = mean(lvr_data$total_price)) %>%
  collect()

a <- taipei_house_mean[order(taipei_house_mean$price_mean, decreasing = TRUE),]
a
barplot(height=a$price_mean, names.arg = a$area, col = as.factor(a$area))



lvr_data %>% 
  group_by("area") %>%
  summarize(price_mean = mean(lvr_data$total_price)) %>%
  arrange(desc(.$price_mean)) %>%
  head()
```

## Demo of magrittr
```{r}
a <- c(1,2,3,4,5)
head(a,3)
a %>% head(3)
3 %>% head(a, .)
```


## 新增欄位
```{r}
printSchema(lvr_data)
showDF(lvr_data)

lvr_data$house_age <-(datediff(date_format(lvr_data$trading_ymd, "yyyy-MM-dd"), date_format(lvr_data$finish_ymd, "yyyy-MM-dd")))/365
?datediff

printSchema(lvr_data)
showDF(lvr_data)
```

## 根據各區計算每月平均價格變化
```{r}
?date_format
lvr_data$trading_ym <- date_format(lvr_data$trading_ymd, "yyyy-MM-01")
printSchema(lvr_data)
showDF(lvr_data)

#method1
mean_prices<-summarize(groupBy(lvr_data, lvr_data$area, lvr_data$trading_ym), price_avg=mean(lvr_data$total_price))

#method2
mean_df <- lvr_data %>% 
  groupBy("area", "trading_ym") %>%
  summarize(price_avg = mean(lvr_data$total_price)) %>%
  collect()

mean_df

```

## SparkSQL
```{r}
createOrReplaceTempView(lvr_data, "lvr_data")
printSchema(lvr_data)
lvr_sql <- sql('SELECT area, AVG(total_price) FROM lvr_data WHERE house_age < 30 GROUP BY area ')
head(lvr_sql)
a <- createExternalTable('lvr_data2', path='lvr_prices.csv', source='csv')
head(lvr_prices)
lvr_sql2 <- sql('SELECT _c0, _c10 FROM lvr_data2')
head(lvr_sql2)
```

## Predict House Price
```{r}

str(lvr_prices)
plot(log(total_price) ~ log(building_sqmeter), data = lvr_prices)
fit <- lm(total_price ~ building_sqmeter, data = lvr_prices)
fit$coefficients[2]
222370/0.3025


```

## Linear Regression
```{r}
library(lars)
data("diabetes")
View(diabetes)
?diabetes

diabetes_all<-data.frame(cbind(diabetes$x, y =diabetes$y))
View(diabetes_all)

outcome_name<-'y'
diabetes_all$sex<-as.numeric(as.factor(diabetes_all$sex))


set.seed(1234)
splitIndex<-base::sample(nrow(diabetes_all),floor(0.75*nrow(diabetes_all)))
train_diabetes<-diabetes_all[splitIndex,]
dim(train_diabetes)

test_diabetes<-diabetes_all[-splitIndex,]
dim(test_diabetes)

train_diabetes_sp<-createDataFrame(train_diabetes)
test_diabetes_sp<-createDataFrame(test_diabetes)

?glm
model <- glm(y~age+sex+bmi+map+tc+ldl+hdl+tch+ltg+glu, data=train_diabetes_sp, family='gaussian')
summary(model)



predictions <- predict(model, newData=test_diabetes_sp)
names(predictions)
predictions_details<-select(predictions, predictions$label,predictions$prediction)

predictions_details<-collect(predictions_details)


mse <- mean(predictions_details$label - predictions_details$prediction)
mse

```



