---
title: "Demo20161015"
author: "David Chiu"
date: "10/14/2016"
output: html_document
---


# DataFrame Introduction
```{r}
height <- 180
heights <- c(166,172,182)
matrix(c(c(80,70,82), c(77,80,82), c(45,56,62)), nrow=3)
data.frame(mary = c(80,70,82), john = c(77,80,82), qoo = c(45,56,62))
```

# Loading IRIS dataset
```{r}
data(iris)
class(iris)
View(iris)
str(iris)
summary(iris)
head(iris)
tail(iris)
?head
head(iris, 10)

```

# Data Manipulation in R
```{r}
#取前三列資料
iris[1:3,]
#取前三列第一行的資料
iris[1:3,1]
#也可以用欄位名稱取值
iris[1:3,"Sepal.Length"]
#取前兩行資料
iris[,1:2]
#取特定欄位向量值
iris$"Sepal.Length"
```

```{r}
#取前五筆包含length 及 width 的資料
five.Sepal.iris <- iris[1:5, c("Sepal.Length", "Sepal.Width")]
five.Sepal.iris

#可以用條件做篩選
setosa.data <- iris[iris$Species=="setosa",1:5]

```

# Data Sorting
```{r}
sort(iris$Sepal.Length, decreasing = TRUE)
head(iris[order(iris$Sepal.Length, decreasing = TRUE),])
```

# Data Visualization
```{r}
#Pie Chart
table.iris = table(iris$Species)
pie(table.iris)

#Histogram
hist(iris$Sepal.Length)

#Box Plot
boxplot(Petal.Width ~ Species, data = iris)

#Scatter Plot
plot(x=iris$Petal.Length, y=iris$Petal.Width, col=iris$Species)


```


## Machine Learning
```{r}
#安裝rpart 套件
#install.packages('rpart')

#讀取rpart 套件
library(rpart)

#建立模型
fit <- rpart(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,data= iris)

#繪製模型
plot(fit, margin = 0.2)
text(fit)

```

## Quantmod
```{r}
# install.packages("quantmod")
library(quantmod)
tw2330 <- getSymbols('2330.TW')

max(`2330.TW`$`2330.TW.Close`)
min(`2330.TW`$`2330.TW.Close`)
summary(`2330.TW`$`2330.TW.Close`)

boxplot(as.data.frame(`2330.TW`$`2330.TW.Close`))

chartSeries(`2330.TW`)
```

# Analyze big data
```
download.file('https://github.com/ywchiu/rcookbook/raw/master/chapter4/purchase_view.tab', 'purchase_view.tab')
purchase <- read.csv('purchase_view.tab', sep='\t')
library(data.table)
system.time(P <-read.csv('purchase_view.tab', sep='\t'))
system.time(DT <- fread('purchase_view.tab'))
```
## R Style
```{r}
# prevent looping, using default function
s = 0 
for (i in seq(1,100)){
  s = s + i
}
s

sum(1:100)

# vectorized programming
b = c()
a = c(1,2,3,4,5)
for (i in a){
  b = c(b, i*i)
}
b

a = c(1,2,3,4,5)
a = a ^ 2
a

# preallocating
b = c()
a = c(1,2,3,4,5)
for (i in a){
  b = c(b, i*i)
}
b

b = c(0,0,0,0,0)
a = c(1,2,3,4,6)
for (i in seq_along(a)){
  b[i] = a[i] ^ 2
}
b




```



